// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.Weather
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("tempC")]
        public double? TempC { get; set; }

        [JsonProperty("tempF")]
        public double? TempF { get; set; }

        [JsonProperty("windMph")]
        public double? WindMph { get; set; }

        [JsonProperty("windKph")]
        public double? WindKph { get; set; }

        [JsonProperty("windDegree")]
        public long? WindDegree { get; set; }

        [JsonProperty("windDir")]
        public string WindDir { get; set; }

        [JsonProperty("pressureMb")]
        public long? PressureMb { get; set; }

        [JsonProperty("pressureIn")]
        public double? PressureIn { get; set; }

        [JsonProperty("precipMm")]
        public long? PrecipMm { get; set; }

        [JsonProperty("precipIn")]
        public long? PrecipIn { get; set; }

        [JsonProperty("feelslikeC")]
        public long? FeelslikeC { get; set; }

        [JsonProperty("feelslikeF")]
        public double? FeelslikeF { get; set; }

        [JsonProperty("visKm")]
        public long? VisKm { get; set; }

        [JsonProperty("visMiles")]
        public long? VisMiles { get; set; }

        [JsonProperty("gustMph")]
        public double? GustMph { get; set; }

        [JsonProperty("gustKph")]
        public double? GustKph { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
